import org.mapsforge.map.reader.MapFile;
import org.mapsforge.map.reader.header.MapFileInfo;
import org.mapsforge.map.reader.header.MapFileHeader;
import org.mapsforge.map.reader.header.SubFileParameter;
import org.mapsforge.core.model.BoundingBox;
import org.mapsforge.core.model.Tag;
import org.mapsforge.core.model.LatLong;

import java.io.File;
import java.util.Date;

/**
 * A utility to analyze and print detailed information about a Mapsforge .map file.
 *
 * This analyzer extracts and displays a comprehensive set of metadata from the map file,
 * including file version, size, creation date, projection, bounding box, tags, and
 * detailed information about each sub-file and its zoom levels.
 *
 * It was determined through analysis that the filenames of the maps being processed
 * follow a specific, proprietary convention:
 *
 * <CountryCode><RegionCode><Constant_00><Date_YYMMDD><GridIdentifier>.map
 *
 * The <GridIdentifier> is a unique, alphanumeric code that corresponds to a specific
 * geographic tile. This identifier is generated by a closed-source, external system
 * and is passed to the map creation tools. It is a "black box" identifier, and its
 * logic cannot be deciphered from the open-source codebase.
 *
 * The "Created By" field within the map file's metadata often contains an abbreviated
 * version of this filename, confirming the link between the filename and the map data.
 */
public class MapDetailAnalyzer {

    public static void main(String[] args) {
        if (args.length != 1) {
            System.out.println("Usage: java -cp <classpath> MapDetailAnalyzer <map-file-path>");
            return;
        }

        File mapFile = new File(args[0]);
        if (!mapFile.exists()) {
            System.out.println("Error: Map file not found at " + args[0]);
            return;
        }

        MapFile map = null;
        try {
            map = new MapFile(mapFile);
            MapFileInfo info = map.getMapFileInfo();
            MapFileHeader header = map.getMapFileHeader();

            System.out.println("=================================================");
            System.out.println(" Detailed Map Analysis for: " + mapFile.getName());
            System.out.println("=================================================");

            // File Version
            System.out.println("File Version: " + info.fileVersion);

            // File Size
            System.out.println("File Size: " + info.fileSize + " bytes");

            // Date of map creation
            System.out.println("Creation Date: " + new Date(info.mapDate));
            
            // Projection
            System.out.println("Projection: " + info.projectionName);

            // Created By
            System.out.println("Created By: " + (info.createdBy != null ? info.createdBy : "N/A"));

            // Comment
            System.out.println("Comment: " + (info.comment != null ? info.comment : "N/A"));
            
            // Languages
            System.out.println("Preferred Languages: " + (info.languagesPreference != null ? info.languagesPreference : "N/A"));

            // Start Position
            if (info.startPosition != null) {
                System.out.println("Start Position: " + info.startPosition.latitude + ", " + info.startPosition.longitude);
            } else {
                System.out.println("Start Position: N/A");
            }
            
            // Start Zoom Level
            if (info.startZoomLevel != null) {
                System.out.println("Start Zoom Level: " + info.startZoomLevel);
            } else {
                 System.out.println("Start Zoom Level: N/A");
            }

            // Bounding Box
            BoundingBox bbox = info.boundingBox;
            if (bbox != null) {
                System.out.println("Bounding Box: MinLat=" + bbox.minLatitude + ", MinLon=" + bbox.minLongitude +
                                   ", MaxLat=" + bbox.maxLatitude + ", MaxLon=" + bbox.maxLongitude);
            }

            // Tile Pixel Size
            System.out.println("Tile Size: " + info.tilePixelSize + "x" + info.tilePixelSize);
            
            // Debug file flag
            System.out.println("Is Debug File: " + info.debugFile);

            // POI Tags
            Tag[] poiTags = info.poiTags;
            if (poiTags != null && poiTags.length > 0) {
                System.out.println("POI Tags ("+ poiTags.length +"):");
                for (Tag tag : poiTags) {
                    System.out.println("  - " + tag.key + "=" + tag.value);
                }
            } else {
                System.out.println("POI Tags: None");
            }

            // Way Tags
            Tag[] wayTags = info.wayTags;
            if (wayTags != null && wayTags.length > 0) {
                System.out.println("Way Tags (" + wayTags.length + "):");
                for (Tag tag : wayTags) {
                    System.out.println("  - " + tag.key + "=" + tag.value);
                }
            } else {
                System.out.println("Way Tags: None");
            }

            System.out.println("\n--- Sub-File Details ---");
            System.out.println("Number of Sub-Files: " + info.numberOfSubFiles);
            for (byte z = 0; z <= info.zoomLevelMax; z++) {
                SubFileParameter subFile = header.getSubFileParameter(z);
                if (subFile != null) {
                    System.out.println("\n[Sub-File for zoom " + z + "]");
                    System.out.println("  Base Zoom Level: " + subFile.baseZoomLevel);
                    System.out.println("  Min Zoom Level: " + subFile.zoomLevelMin);
                    System.out.println("  Max Zoom Level: " + subFile.zoomLevelMax);
                    System.out.println("  Start Address: " + subFile.startAddress);
                    System.out.println("  Sub-File Size: " + subFile.subFileSize + " bytes");
                    System.out.println("  Number of Blocks: " + subFile.numberOfBlocks);
                }
            }


            System.out.println("=================================================");

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (map != null) {
                map.close();
            }
        }
    }
} 